generator:
  class: sfPropelGenerator
  param:
    model_class:           Category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Category
    plural:                Categorys
    route_prefix:          category
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        parent_id:         { label: Top-категория }
        name:              { label: Имя }
        slug:              { label: Slug }
        car_category_list: { label: Марка авто }
      list:
        title:             Категории запчастей
      filter:  ~
      form:    ~
      edit:
        title:             Редактирование категории
      new:
        title:             Новая категория
